### ISSUE TITLE
Pass data to the consumer (XDM)

### ISSUE THREAD

**Issue by danielpuglisi** [Octo-Labs/easymarklet#2]
> First things first: Thank you for open sourcing this gem. Saved me a lot of time.

I'm trying to build a XDM bookmarklet which allows the currently logged in user of the application to save the link of the currently open website to one of his lists.

I'm currently fetching the lists through an additional JSON request while initializing the `consumer`. My question is, is there a way to avoid the additional request and load the data directly?

And while we're at it, is there any way to use the `producer`s `index.html.erb` file as the bookmarklets initial layout instead of generating everything in Javascript?

**Comment by jagthedrummer** [comment]
Hi, @danielpuglisi, I'm glad you've found this useful.  Have you looked at the iframe example on the Foo vs Baz demo site?  It sounds like that's going to be what you're looking for.  

http://foo-vs-baz.herokuapp.com/iframe

Let me know if that's not helpful and you're looking for something else.

**Comment by danielpuglisi** [comment]
@jagthedrummer thanks, that's what I was looking for. Should have looked at the other examples before diving in :thumbsup:
